// Total snippets: 12
// -----------------------------------------
// Snippet #0 platforms ffffffff:
Keywords always included into build: FOG_EXP FOG_EXP2 FOG_LINEAR

1 keyword variants used in scene:

<no keywords defined>


// -----------------------------------------
// Snippet #1 platforms ffffffff:
Keywords stripped away when not used: _ALPHABLEND_ON _ALPHAPREMULTIPLY_ON _ALPHATEST_ON _DETAIL_MULX2 _EMISSION _GLOSSYREFLECTIONS_OFF _METALLICGLOSSMAP _NORMALMAP _PARALLAXMAP _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A _SPECULARHIGHLIGHTS_OFF
Keywords always included into build: FOG_EXP FOG_EXP2 FOG_LINEAR INSTANCING_ON
Builtin keywords used: DIRECTIONAL DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_ON LIGHTMAP_ON LIGHTMAP_SHADOW_MIXING LIGHTPROBE_SH SHADOWS_SCREEN SHADOWS_SHADOWMASK VERTEXLIGHT_ON

36 keyword variants used in scene:

DIRECTIONAL
DIRECTIONAL LIGHTPROBE_SH _EMISSION
DIRECTIONAL LIGHTPROBE_SH
DIRECTIONAL DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_ON _EMISSION
DIRECTIONAL DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_ON
DIRECTIONAL DIRLIGHTMAP_COMBINED LIGHTMAP_ON _EMISSION
DIRECTIONAL DIRLIGHTMAP_COMBINED LIGHTMAP_ON
DIRECTIONAL DIRLIGHTMAP_COMBINED LIGHTMAP_ON LIGHTPROBE_SH _EMISSION
DIRECTIONAL DIRLIGHTMAP_COMBINED LIGHTMAP_ON LIGHTPROBE_SH
DIRECTIONAL DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_ON LIGHTMAP_ON _EMISSION
DIRECTIONAL DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_ON LIGHTMAP_ON
DIRECTIONAL SHADOWS_SCREEN _EMISSION
DIRECTIONAL SHADOWS_SCREEN
DIRECTIONAL LIGHTPROBE_SH SHADOWS_SCREEN _EMISSION
DIRECTIONAL LIGHTPROBE_SH SHADOWS_SCREEN
DIRECTIONAL DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_ON SHADOWS_SCREEN _EMISSION
DIRECTIONAL DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_ON SHADOWS_SCREEN
DIRECTIONAL DIRLIGHTMAP_COMBINED LIGHTMAP_ON SHADOWS_SCREEN _EMISSION
DIRECTIONAL DIRLIGHTMAP_COMBINED LIGHTMAP_ON SHADOWS_SCREEN
DIRECTIONAL DIRLIGHTMAP_COMBINED LIGHTMAP_ON LIGHTPROBE_SH SHADOWS_SCREEN _EMISSION
DIRECTIONAL DIRLIGHTMAP_COMBINED LIGHTMAP_ON LIGHTPROBE_SH SHADOWS_SCREEN
DIRECTIONAL DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_ON LIGHTMAP_ON SHADOWS_SCREEN _EMISSION
DIRECTIONAL DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_ON LIGHTMAP_ON SHADOWS_SCREEN
DIRECTIONAL VERTEXLIGHT_ON _EMISSION
DIRECTIONAL VERTEXLIGHT_ON
DIRECTIONAL LIGHTPROBE_SH VERTEXLIGHT_ON _EMISSION
DIRECTIONAL LIGHTPROBE_SH VERTEXLIGHT_ON
DIRECTIONAL DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_ON VERTEXLIGHT_ON _EMISSION
DIRECTIONAL DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_ON VERTEXLIGHT_ON
DIRECTIONAL SHADOWS_SCREEN VERTEXLIGHT_ON _EMISSION
DIRECTIONAL SHADOWS_SCREEN VERTEXLIGHT_ON
DIRECTIONAL LIGHTPROBE_SH SHADOWS_SCREEN VERTEXLIGHT_ON _EMISSION
DIRECTIONAL LIGHTPROBE_SH SHADOWS_SCREEN VERTEXLIGHT_ON
DIRECTIONAL DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_ON SHADOWS_SCREEN VERTEXLIGHT_ON _EMISSION
DIRECTIONAL DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_ON SHADOWS_SCREEN VERTEXLIGHT_ON
DIRECTIONAL _EMISSION


// -----------------------------------------
// Snippet #2 platforms ffffffff:
Keywords always included into build: INSTANCING_ON
Builtin keywords used: SHADOWS_CUBE SHADOWS_DEPTH

2 keyword variants used in scene:

SHADOWS_DEPTH
SHADOWS_CUBE


// -----------------------------------------
// Snippet #3 platforms ffffffff:
Keywords stripped away when not used: _ALPHABLEND_ON _ALPHAPREMULTIPLY_ON _ALPHATEST_ON _DETAIL_MULX2 _METALLICGLOSSMAP _NORMALMAP _PARALLAXMAP _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A _SPECULARHIGHLIGHTS_OFF
Keywords always included into build: FOG_EXP FOG_EXP2 FOG_LINEAR
Builtin keywords used: DIRECTIONAL DIRECTIONAL_COOKIE LIGHTMAP_SHADOW_MIXING POINT POINT_COOKIE SHADOWS_CUBE SHADOWS_DEPTH SHADOWS_SCREEN SHADOWS_SHADOWMASK SHADOWS_SOFT SPOT

13 keyword variants used in scene:

POINT
DIRECTIONAL
SPOT
POINT_COOKIE
DIRECTIONAL_COOKIE
SHADOWS_DEPTH SPOT
SHADOWS_DEPTH SHADOWS_SOFT SPOT
DIRECTIONAL SHADOWS_SCREEN
DIRECTIONAL_COOKIE SHADOWS_SCREEN
POINT SHADOWS_CUBE
POINT SHADOWS_CUBE SHADOWS_SOFT
POINT_COOKIE SHADOWS_CUBE
POINT_COOKIE SHADOWS_CUBE SHADOWS_SOFT


// -----------------------------------------
// Snippet #4 platforms ffffffff:
Keywords stripped away when not used: _ALPHABLEND_ON _ALPHAPREMULTIPLY_ON _ALPHATEST_ON _METALLICGLOSSMAP _PARALLAXMAP _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A
Keywords always included into build: INSTANCING_ON
Builtin keywords used: SHADOWS_CUBE SHADOWS_DEPTH

2 keyword variants used in scene:

SHADOWS_DEPTH
SHADOWS_CUBE


// -----------------------------------------
// Snippet #5 platforms ffffffff:
Keywords always included into build: FOG_EXP FOG_EXP2 FOG_LINEAR POINT SPOT

3 keyword variants used in scene:

<no keywords defined>
POINT
SPOT


// -----------------------------------------
// Snippet #6 platforms fffffbff:
Keywords stripped away when not used: _ALPHABLEND_ON _ALPHAPREMULTIPLY_ON _ALPHATEST_ON _DETAIL_MULX2 _EMISSION _METALLICGLOSSMAP _NORMALMAP _PARALLAXMAP _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A _SPECULARHIGHLIGHTS_OFF
Keywords always included into build: INSTANCING_ON
Builtin keywords used: DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_ON LIGHTMAP_ON LIGHTPROBE_SH SHADOWS_SHADOWMASK UNITY_HDR_ON

24 keyword variants used in scene:

<no keywords defined>
LIGHTPROBE_SH _EMISSION
LIGHTPROBE_SH
DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_ON _EMISSION
DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_ON
DIRLIGHTMAP_COMBINED LIGHTMAP_ON _EMISSION
DIRLIGHTMAP_COMBINED LIGHTMAP_ON
DIRLIGHTMAP_COMBINED LIGHTMAP_ON LIGHTPROBE_SH _EMISSION
DIRLIGHTMAP_COMBINED LIGHTMAP_ON LIGHTPROBE_SH
DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_ON LIGHTMAP_ON _EMISSION
DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_ON LIGHTMAP_ON
UNITY_HDR_ON _EMISSION
UNITY_HDR_ON
LIGHTPROBE_SH UNITY_HDR_ON _EMISSION
LIGHTPROBE_SH UNITY_HDR_ON
DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_ON UNITY_HDR_ON _EMISSION
DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_ON UNITY_HDR_ON
DIRLIGHTMAP_COMBINED LIGHTMAP_ON UNITY_HDR_ON _EMISSION
DIRLIGHTMAP_COMBINED LIGHTMAP_ON UNITY_HDR_ON
DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_ON LIGHTMAP_ON UNITY_HDR_ON _EMISSION
DIRLIGHTMAP_COMBINED DYNAMICLIGHTMAP_ON LIGHTMAP_ON UNITY_HDR_ON
DIRLIGHTMAP_COMBINED LIGHTMAP_ON LIGHTPROBE_SH UNITY_HDR_ON _EMISSION
DIRLIGHTMAP_COMBINED LIGHTMAP_ON LIGHTPROBE_SH UNITY_HDR_ON
_EMISSION


// -----------------------------------------
// Snippet #7 platforms ffffffff:
Keywords stripped away when not used: EDITOR_VISUALIZATION _DETAIL_MULX2 _EMISSION _METALLICGLOSSMAP _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A

2 keyword variants used in scene:

<no keywords defined>
_EMISSION


// -----------------------------------------
// Snippet #8 platforms ffffffff:
Keywords stripped away when not used: _ALPHABLEND_ON _ALPHAPREMULTIPLY_ON _ALPHATEST_ON _EMISSION _GLOSSYREFLECTIONS_OFF _METALLICGLOSSMAP _NORMALMAP _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A _SPECULARHIGHLIGHTS_OFF
Keywords always included into build: FOG_EXP FOG_EXP2 FOG_LINEAR
Builtin keywords used: DIRECTIONAL DYNAMICLIGHTMAP_ON LIGHTMAP_ON LIGHTMAP_SHADOW_MIXING LIGHTPROBE_SH SHADOWS_SCREEN SHADOWS_SHADOWMASK VERTEXLIGHT_ON

16 keyword variants used in scene:

DIRECTIONAL
DIRECTIONAL LIGHTPROBE_SH _EMISSION
DIRECTIONAL LIGHTPROBE_SH
DIRECTIONAL SHADOWS_SCREEN _EMISSION
DIRECTIONAL SHADOWS_SCREEN
DIRECTIONAL LIGHTPROBE_SH SHADOWS_SCREEN _EMISSION
DIRECTIONAL LIGHTPROBE_SH SHADOWS_SCREEN
DIRECTIONAL VERTEXLIGHT_ON _EMISSION
DIRECTIONAL VERTEXLIGHT_ON
DIRECTIONAL LIGHTPROBE_SH VERTEXLIGHT_ON _EMISSION
DIRECTIONAL LIGHTPROBE_SH VERTEXLIGHT_ON
DIRECTIONAL SHADOWS_SCREEN VERTEXLIGHT_ON _EMISSION
DIRECTIONAL SHADOWS_SCREEN VERTEXLIGHT_ON
DIRECTIONAL LIGHTPROBE_SH SHADOWS_SCREEN VERTEXLIGHT_ON _EMISSION
DIRECTIONAL LIGHTPROBE_SH SHADOWS_SCREEN VERTEXLIGHT_ON
DIRECTIONAL _EMISSION


// -----------------------------------------
// Snippet #9 platforms ffffffff:
Keywords stripped away when not used: _ALPHABLEND_ON _ALPHAPREMULTIPLY_ON _ALPHATEST_ON _DETAIL_MULX2 _METALLICGLOSSMAP _NORMALMAP _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A _SPECULARHIGHLIGHTS_OFF
Keywords always included into build: FOG_EXP FOG_EXP2 FOG_LINEAR
Builtin keywords used: DIRECTIONAL DIRECTIONAL_COOKIE LIGHTMAP_SHADOW_MIXING POINT POINT_COOKIE SHADOWS_CUBE SHADOWS_DEPTH SHADOWS_SCREEN SHADOWS_SHADOWMASK SPOT

10 keyword variants used in scene:

POINT
DIRECTIONAL
SPOT
POINT_COOKIE
DIRECTIONAL_COOKIE
SHADOWS_DEPTH SPOT
DIRECTIONAL SHADOWS_SCREEN
DIRECTIONAL_COOKIE SHADOWS_SCREEN
POINT SHADOWS_CUBE
POINT_COOKIE SHADOWS_CUBE


// -----------------------------------------
// Snippet #10 platforms ffffffff:
Keywords stripped away when not used: _ALPHABLEND_ON _ALPHAPREMULTIPLY_ON _ALPHATEST_ON _METALLICGLOSSMAP _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A
Builtin keywords used: SHADOWS_CUBE SHADOWS_DEPTH

2 keyword variants used in scene:

SHADOWS_DEPTH
SHADOWS_CUBE


// -----------------------------------------
// Snippet #11 platforms ffffffff:
Keywords stripped away when not used: EDITOR_VISUALIZATION _DETAIL_MULX2 _EMISSION _METALLICGLOSSMAP _SMOOTHNESS_TEXTURE_ALBEDO_CHANNEL_A

2 keyword variants used in scene:

<no keywords defined>
_EMISSION


